version: '3'

services:
  laravel:
    container_name: laravel
    image: kabunx/laravel:alpine
    build: 
      context: ./laravel
    volumes:
      - /var/php/mpm-service:/var/www/mpm-service
    ports:
      - "9001-9009:9001-9009"
    networks:
      - internal
      - external
    restart: always

  yii:
    container_name: yii
    image: kabunx/yii:alpine
    build: 
      context: ./yii
    volumes:
      - /var/php/hr-service:/var/www/hr-service
      - /var/php/operation-service:/var/www/operation-service
    ports:
      - "9010-9019:9010-9019"
    networks:
      - internal
      - external
    restart: always

networks:
  internal:
  external: