version: '3'

services:
  # 数据库服务
  mysql:
    container_name: mysql
    image: kabunx/mysql:5.7
    build:
      context: mysql
      args:
        - MYSQL_TIMEZONE=Asia/Shanghai
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - /data/volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal
    restart: always

  # 缓存服务
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - /data/volumes/redis:/data
    ports:
      - "6379:6379"
    networks:
      - internal
    restart: always

  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - ./env/postgres.env
    volumes:
      - /data/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
    restart: always

networks:
  internal:
  external: