server:
  port: 8089
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    address: mysql:3306
    database: dev_canal_manager
    username: canal
    password: canal
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/dev_canal_manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1

canal:
  adminUser: admin
  adminPasswd: admin