## 需要安装 REST Client 插件

###

GET http://www.baidu.com HTTP/1.1


## -n 发起的请求数，-c 并发数

ab -n 1000 -c 100 -p "search.txt" -T "application/json" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Authorization: " "https://api.kabunx.dev"